{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "NAME        STATUS   ROLES                  AGE    VERSION   INTERNAL-IP       EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME\n",
      "openbox00   Ready    control-plane,master   164d   v1.20.0   192.168.199.173   <none>        Ubuntu 20.04.1 LTS   5.4.0-52-generic   docker://19.3.13\n",
      "openbox01   Ready    control-plane,master   164d   v1.20.0   192.168.199.180   <none>        Ubuntu 20.04.1 LTS   5.4.0-52-generic   docker://19.3.8\n",
      "openbox02   Ready    control-plane,master   164d   v1.20.0   192.168.199.249   <none>        Ubuntu 20.04 LTS     5.4.0-26-generic   docker://19.3.13\n"
     ]
    }
   ],
   "source": [
    "!kubectl get node -owide"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "No resources found in istio-system namespace.\n"
     ]
    }
   ],
   "source": [
    "!kubectl get pod -n istio-system -owide "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "No resources found in gisbook namespace.\n"
     ]
    }
   ],
   "source": [
    "!kubectl get pod -n gisbook -owide"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "aksusbd-2.4.1-i386/\n",
      "aksusbd-2.4.1-i386/dinst\n",
      "aksusbd-2.4.1-i386/winehasp\n",
      "aksusbd-2.4.1-i386/hasplmd\n",
      "aksusbd-2.4.1-i386/haspvlib_99235.so\n",
      "aksusbd-2.4.1-i386/dunst\n",
      "aksusbd-2.4.1-i386/hasp.rules\n",
      "aksusbd-2.4.1-i386/SuperMap Trial License .v2c\n",
      "aksusbd-2.4.1-i386/aksusbd.rc\n",
      "aksusbd-2.4.1-i386/hasp_update\n",
      "aksusbd-2.4.1-i386/aksusbd\n",
      "dpkg-query: no packages found matching aksusbd\n",
      "Removing files ...\n",
      "Done\n",
      "dpkg-query: no packages found matching aksusbd\n",
      "Copy AKSUSB daemon to /usr/sbin ...\n",
      "Copy WINEHASP daemon to /usr/sbin ...\n",
      "Copy HASPLMD daemon to /usr/sbin ...\n",
      "Copy start-up script to /etc/init.d ...\n",
      "Link HASP SRM runtime environment startup script to system startup folder\n",
      "Starting HASP SRM runtime environment...\n",
      "Starting AKSUSB daemon: .\n",
      "Starting WINEHASP daemon: .\n",
      "Starting HASPLM daemon: .\n",
      "Coping VLIB...\n",
      "Installing v2c...\n",
      "Done\n",
      "\n",
      "ISERVER_DATASCIENCE_IS_RUNTIME \n",
      "运行数据科学服务\n",
      "Using Notebook Home /opt/datascience\n",
      "Using Sample Data Directory /opt/datascience/sampledata\n",
      "Using Notebook Directory /opt/datascience/notebooks\n",
      "/opt/datascience/conf/jupyterhub_config.py\n",
      "/opt/datascience/confDir/jupyterhub_config.py\n",
      "/opt/datascience/miniconda/lib/python3.6/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.25.8) or chardet (3.0.4) doesn't match a supported version!\n",
      "  RequestsDependencyWarning)\n",
      "Loading /etc/jupyterhub/config/values.yaml\n",
      "Loading /etc/jupyterhub/secret/values.yaml\n",
      "[I 2020-06-24 09:52:42.367 JupyterHub app:2120] Using Authenticator: jupyterhub.auth.PAMAuthenticator-1.0.0\n",
      "[I 2020-06-24 09:52:42.367 JupyterHub app:2120] Using Spawner: kubespawner.spawner.KubeSpawner\n",
      "[I 2020-06-24 09:52:42.367 JupyterHub app:1302] Writing cookie_secret to /opt/datascience/bin/jupyterhub_cookie_secret\n",
      "[I 2020-06-24 09:52:42.392 alembic.runtime.migration migration:154] Context impl SQLiteImpl.\n",
      "[I 2020-06-24 09:52:42.392 alembic.runtime.migration migration:161] Will assume non-transactional DDL.\n",
      "[I 2020-06-24 09:52:42.398 alembic.runtime.migration migration:513] Running stamp_revision  -> 4dc2d5a8c53c\n",
      "[W 2020-06-24 09:52:42.433 JupyterHub app:1487] JupyterHub.hub_connect_port is deprecated as of 0.9. Use JupyterHub.hub_connect_url to fully specify the URL for connecting to the Hub.\n",
      "[W 2020-06-24 09:52:42.435 JupyterHub app:1532] No admin users, admin interface will be unavailable.\n",
      "[W 2020-06-24 09:52:42.435 JupyterHub app:1534] Add any administrative users to `c.Authenticator.admin_users` in config.\n",
      "[I 2020-06-24 09:52:42.435 JupyterHub app:1563] Not using whitelist. Any authenticated user will be allowed.\n",
      "[I 2020-06-24 09:52:42.468 JupyterHub app:2337] Hub API listening on http://0.0.0.0:8081/hub/\n",
      "[I 2020-06-24 09:52:42.468 JupyterHub app:2339] Private Hub API connect url http://10.103.190.208:8081/hub/\n",
      "[I 2020-06-24 09:52:42.468 JupyterHub app:2352] Not starting proxy\n",
      "[I 2020-06-24 09:52:42.468 JupyterHub app:2362] Starting managed service cull-idle\n",
      "[I 2020-06-24 09:52:42.469 JupyterHub service:316] Starting service 'cull-idle': ['/usr/local/bin/cull_idle_servers.py', '--url=http://127.0.0.1:8081/hub/api', '--timeout=3600', '--cull-every=600', '--concurrency=10']\n",
      "[I 2020-06-24 09:52:42.470 JupyterHub service:121] Spawning /usr/local/bin/cull_idle_servers.py --url=http://127.0.0.1:8081/hub/api --timeout=3600 --cull-every=600 --concurrency=10\n",
      "[I 2020-06-24 09:52:42.476 JupyterHub proxy:319] Checking routes\n",
      "[I 2020-06-24 09:52:42.476 JupyterHub app:2422] JupyterHub is now running at http://10.100.133.24:80/\n",
      "[I 2020-06-24 09:52:42.589 JupyterHub log:174] 200 GET /hub/api/users (cull-idle@127.0.0.1) 8.14ms\n",
      "[I 2020-06-24 09:52:43.026 JupyterHub log:174] 200 GET /hub/setup/systemenvinfo (@10.244.0.1) 26.97ms\n",
      "[W 2020-06-24 09:52:43.072 JupyterHub log:174] 403 GET /hub/metrics (@10.244.1.133) 41.55ms\n",
      "[I 2020-06-24 09:52:49.381 JupyterHub log:174] 302 GET /hub/home -> /hub/login?next=%2Fhub%2Fhome (@10.244.0.1) 2.48ms\n",
      "[I 2020-06-24 09:52:49.424 JupyterHub log:174] 200 GET /hub/login?next=%2Fhub%2Fhome (@10.244.0.1) 20.81ms\n",
      "[W 2020-06-24 09:52:58.019 JupyterHub log:174] 403 GET /hub/metrics (@10.244.1.133) 3.24ms\n",
      "[W 2020-06-24 09:53:00.992 JupyterHub auth:908] PAM Authentication failed (supermap@10.244.0.1): [PAM Error 3] Error in service module\n",
      "[W 2020-06-24 09:53:00.993 JupyterHub base:670] Failed login for supermap\n",
      "[I 2020-06-24 09:53:00.996 JupyterHub log:174] 200 POST /hub/login?next=%2Fhub%2Fhome (@10.244.0.1) 2322.97ms\n",
      "[W 2020-06-24 09:53:13.020 JupyterHub log:174] 403 GET /hub/metrics (@10.244.1.133) 3.14ms\n",
      "[W 2020-06-24 09:53:22.992 JupyterHub auth:908] PAM Authentication failed (supermap@10.244.0.1): [PAM Error 3] Error in service module\n",
      "[W 2020-06-24 09:53:22.993 JupyterHub base:670] Failed login for supermap\n",
      "[I 2020-06-24 09:53:22.996 JupyterHub log:174] 200 POST /hub/login?next=%2Fhub%2Fhome (@10.244.0.1) 3149.18ms\n",
      "[W 2020-06-24 09:53:28.020 JupyterHub log:174] 403 GET /hub/metrics (@10.244.1.133) 3.14ms\n",
      "[W 2020-06-24 09:53:33.469 JupyterHub auth:908] PAM Authentication failed (supermap@10.244.0.1): [PAM Error 3] Error in service module\n",
      "[W 2020-06-24 09:53:33.469 JupyterHub base:670] Failed login for supermap\n",
      "[I 2020-06-24 09:53:33.473 JupyterHub log:174] 200 POST /hub/login?next=%2Fhub%2Fhome (@10.244.0.1) 3412.37ms\n",
      "[W 2020-06-24 09:53:36.915 JupyterHub auth:908] PAM Authentication failed (supermapmap@10.244.0.1): [PAM Error 3] Error in service module\n",
      "[W 2020-06-24 09:53:36.916 JupyterHub base:670] Failed login for supermapmap\n",
      "[I 2020-06-24 09:53:36.919 JupyterHub log:174] 200 POST /hub/login?next=%2Fhub%2Fhome (@10.244.0.1) 2240.07ms\n",
      "[I 2020-06-24 09:53:42.483 JupyterHub proxy:319] Checking routes\n",
      "[W 2020-06-24 09:53:43.019 JupyterHub log:174] 403 GET /hub/metrics (@10.244.1.133) 3.15ms\n",
      "[W 2020-06-24 09:53:46.220 JupyterHub auth:908] PAM Authentication failed (supermapmap@10.244.0.1): [PAM Error 3] Error in service module\n",
      "[W 2020-06-24 09:53:46.221 JupyterHub base:670] Failed login for supermapmap\n",
      "[I 2020-06-24 09:53:46.224 JupyterHub log:174] 200 POST /hub/login?next=%2Fhub%2Fhome (@10.244.0.1) 3089.13ms\n",
      "[W 2020-06-24 09:53:57.720 JupyterHub auth:908] PAM Authentication failed (supermap@10.244.0.1): [PAM Error 3] Error in service module\n",
      "[W 2020-06-24 09:53:57.721 JupyterHub base:670] Failed login for supermap\n",
      "[I 2020-06-24 09:53:57.723 JupyterHub log:174] 200 POST /hub/login?next=%2Fhub%2Fhome (@10.244.0.1) 2562.49ms\n",
      "[W 2020-06-24 09:53:58.020 JupyterHub log:174] 403 GET /hub/metrics (@10.244.1.133) 3.18ms\n",
      "[W 2020-06-24 09:54:13.018 JupyterHub log:174] 403 GET /hub/metrics (@10.244.1.133) 1.18ms\n",
      "[W 2020-06-24 09:54:28.020 JupyterHub log:174] 403 GET /hub/metrics (@10.244.1.133) 3.13ms\n",
      "[I 2020-06-24 09:54:42.482 JupyterHub proxy:319] Checking routes\n",
      "[W 2020-06-24 09:54:43.020 JupyterHub log:174] 403 GET /hub/metrics (@10.244.1.133) 3.17ms\n",
      "[W 2020-06-24 09:54:58.020 JupyterHub log:174] 403 GET /hub/metrics (@10.244.1.133) 3.18ms\n",
      "[W 2020-06-24 09:55:13.021 JupyterHub log:174] 403 GET /hub/metrics (@10.244.1.133) 3.80ms\n",
      "[W 2020-06-24 09:55:28.021 JupyterHub log:174] 403 GET /hub/metrics (@10.244.1.133) 3.14ms\n",
      "[I 2020-06-24 09:55:42.480 JupyterHub proxy:319] Checking routes\n",
      "[W 2020-06-24 09:55:43.021 JupyterHub log:174] 403 GET /hub/metrics (@10.244.1.133) 3.22ms\n",
      "[W 2020-06-24 09:55:58.021 JupyterHub log:174] 403 GET /hub/metrics (@10.244.1.133) 3.13ms\n",
      "[W 2020-06-24 09:56:13.021 JupyterHub log:174] 403 GET /hub/metrics (@10.244.1.133) 3.13ms\n",
      "[W 2020-06-24 09:56:28.021 JupyterHub log:174] 403 GET /hub/metrics (@10.244.1.133) 3.15ms\n",
      "[I 2020-06-24 09:56:42.480 JupyterHub proxy:319] Checking routes\n",
      "[W 2020-06-24 09:56:43.021 JupyterHub log:174] 403 GET /hub/metrics (@10.244.1.133) 3.21ms\n",
      "[W 2020-06-24 09:56:58.022 JupyterHub log:174] 403 GET /hub/metrics (@10.244.1.133) 3.15ms\n",
      "[W 2020-06-24 09:57:13.022 JupyterHub log:174] 403 GET /hub/metrics (@10.244.1.133) 3.08ms\n",
      "[W 2020-06-24 09:57:28.021 JupyterHub log:174] 403 GET /hub/metrics (@10.244.1.133) 2.39ms\n",
      "[I 2020-06-24 09:57:42.480 JupyterHub proxy:319] Checking routes\n",
      "[W 2020-06-24 09:57:43.022 JupyterHub log:174] 403 GET /hub/metrics (@10.244.1.133) 3.10ms\n",
      "[W 2020-06-24 09:57:43.478 JupyterHub auth:908] PAM Authentication failed (admin@10.244.0.1): [PAM Error 3] Error in service module\n",
      "[W 2020-06-24 09:57:43.479 JupyterHub base:670] Failed login for admin\n",
      "[I 2020-06-24 09:57:43.481 JupyterHub log:174] 200 POST /hub/login?next=%2Fhub%2Fhome (@10.244.0.1) 2896.45ms\n",
      "[W 2020-06-24 09:57:58.020 JupyterHub log:174] 403 GET /hub/metrics (@10.244.1.133) 1.38ms\n",
      "[I 2020-06-24 09:58:03.712 JupyterHub log:174] 302 GET /hub/ -> /setup (@10.244.0.1) 2.41ms\n",
      "[I 2020-06-24 09:58:03.729 JupyterHub log:174] 302 GET /setup -> /hub/setup (@10.244.0.1) 1.79ms\n",
      "[I 2020-06-24 09:58:03.747 JupyterHub log:174] 302 GET /hub/setup -> /home (@10.244.0.1) 8.18ms\n",
      "[I 2020-06-24 09:58:03.801 JupyterHub log:174] 302 GET /home -> /hub/home (@10.244.0.1) 0.61ms\n",
      "[I 2020-06-24 09:58:03.970 JupyterHub log:174] 302 GET /hub/home -> /hub/login?next=%2Fhub%2Fhome (@10.244.0.1) 2.29ms\n",
      "[I 2020-06-24 09:58:03.986 JupyterHub log:174] 200 GET /hub/login?next=%2Fhub%2Fhome (@10.244.0.1) 3.55ms\n",
      "[W 2020-06-24 09:58:13.026 JupyterHub log:174] 403 GET /hub/metrics (@10.244.1.133) 3.13ms\n",
      "[W 2020-06-24 09:58:28.022 JupyterHub log:174] 403 GET /hub/metrics (@10.244.1.133) 3.10ms\n",
      "[I 2020-06-24 09:58:42.480 JupyterHub proxy:319] Checking routes\n",
      "[W 2020-06-24 09:58:43.022 JupyterHub log:174] 403 GET /hub/metrics (@10.244.1.133) 3.23ms\n",
      "[W 2020-06-24 09:58:58.021 JupyterHub log:174] 403 GET /hub/metrics (@10.244.1.133) 3.12ms\n",
      "[W 2020-06-24 09:59:13.021 JupyterHub log:174] 403 GET /hub/metrics (@10.244.1.133) 4.08ms\n"
     ]
    }
   ],
   "source": [
    "!kubectl logs pod/hub-5dfc7d46f8-wgldm -n gisbook"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {
    "collapsed": true,
    "jupyter": {
     "outputs_hidden": true
    }
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Name:         hook-image-puller-9pg6f\n",
      "Namespace:    default\n",
      "Priority:     0\n",
      "Node:         openbox00/192.168.199.173\n",
      "Start Time:   Wed, 24 Jun 2020 16:40:26 +0800\n",
      "Labels:       app=iserver-datascience\n",
      "              component=hook-image-puller\n",
      "              controller-revision-hash=64f6c975f8\n",
      "              istio.io/rev=default\n",
      "              pod-template-generation=1\n",
      "              release=gisbook\n",
      "              security.istio.io/tlsMode=istio\n",
      "              service.istio.io/canonical-name=iserver-datascience\n",
      "              service.istio.io/canonical-revision=latest\n",
      "Annotations:  sidecar.istio.io/status:\n",
      "                {\"version\":\"e16b88389e2d0f30d103af853bdac6a41c399031fafef687a65ce53a7ee83d33\",\"initContainers\":[\"istio-init\"],\"containers\":[\"istio-proxy\"]...\n",
      "Status:       Running\n",
      "IP:           10.244.0.3\n",
      "IPs:\n",
      "  IP:           10.244.0.3\n",
      "Controlled By:  DaemonSet/hook-image-puller\n",
      "Init Containers:\n",
      "  image-pull-singleuser:\n",
      "    Container ID:  docker://81960ce248d6ec6b322c771785dc11bb6cb5184eb368a00f4f2bc2cc55d41fbc\n",
      "    Image:         registry.cn-beijing.aliyuncs.com/supermap/iserver-datascience:20.03.26\n",
      "    Image ID:      docker-pullable://registry.cn-beijing.aliyuncs.com/supermap/iserver-datascience@sha256:87aa1a7ad766f970822665c58c73051a17c2f782c9d16bbb52a329f5922fd37d\n",
      "    Port:          <none>\n",
      "    Host Port:     <none>\n",
      "    Command:\n",
      "      /bin/sh\n",
      "      -c\n",
      "      echo \"Pulling complete\"\n",
      "    State:          Terminated\n",
      "      Reason:       Completed\n",
      "      Exit Code:    0\n",
      "      Started:      Wed, 24 Jun 2020 16:40:27 +0800\n",
      "      Finished:     Wed, 24 Jun 2020 16:40:27 +0800\n",
      "    Ready:          True\n",
      "    Restart Count:  0\n",
      "    Environment:    <none>\n",
      "    Mounts:         <none>\n",
      "  image-pull-metadata-block:\n",
      "    Container ID:  docker://3d649c1a18df0c7939734e9d118f45e9ea6cff0196b593728735c30d3c431eab\n",
      "    Image:         hub-mirror.c.163.com/jupyterhub/k8s-network-tools:cc865bd\n",
      "    Image ID:      docker-pullable://hub-mirror.c.163.com/jupyterhub/k8s-network-tools@sha256:7b83c17f7222575fba51eed654b226876bf15b2b06aeb3427e2cead08eaf6ba3\n",
      "    Port:          <none>\n",
      "    Host Port:     <none>\n",
      "    Command:\n",
      "      /bin/sh\n",
      "      -c\n",
      "      echo \"Pulling complete\"\n",
      "    State:          Terminated\n",
      "      Reason:       Completed\n",
      "      Exit Code:    0\n",
      "      Started:      Wed, 24 Jun 2020 16:40:33 +0800\n",
      "      Finished:     Wed, 24 Jun 2020 16:40:33 +0800\n",
      "    Ready:          True\n",
      "    Restart Count:  0\n",
      "    Environment:    <none>\n",
      "    Mounts:         <none>\n",
      "  istio-init:\n",
      "    Container ID:  docker://0ab45935d3cb2b0758f16a8505f95e8cafbb3e715581aca8d7bccd44d5bbfee1\n",
      "    Image:         docker.io/istio/proxyv2:1.6.3\n",
      "    Image ID:      docker-pullable://istio/proxyv2@sha256:d082c3eea9c12e2f1bf6e4361509453a87e495d12146a1702d79e549098b8951\n",
      "    Port:          <none>\n",
      "    Host Port:     <none>\n",
      "    Args:\n",
      "      istio-iptables\n",
      "      -p\n",
      "      15001\n",
      "      -z\n",
      "      15006\n",
      "      -u\n",
      "      1337\n",
      "      -m\n",
      "      REDIRECT\n",
      "      -i\n",
      "      *\n",
      "      -x\n",
      "      \n",
      "      -b\n",
      "      *\n",
      "      -d\n",
      "      15090,15021,15020\n",
      "    State:          Terminated\n",
      "      Reason:       Completed\n",
      "      Exit Code:    0\n",
      "      Started:      Wed, 24 Jun 2020 16:41:12 +0800\n",
      "      Finished:     Wed, 24 Jun 2020 16:41:13 +0800\n",
      "    Ready:          True\n",
      "    Restart Count:  0\n",
      "    Limits:\n",
      "      cpu:     100m\n",
      "      memory:  50Mi\n",
      "    Requests:\n",
      "      cpu:     10m\n",
      "      memory:  10Mi\n",
      "    Environment:\n",
      "      DNS_AGENT:  \n",
      "    Mounts:       <none>\n",
      "Containers:\n",
      "  pause:\n",
      "    Container ID:   docker://07a4492d01a5e6bf73e6bf35bdd45897157cd4fa23d21bb90bc33668cb3ab2b3\n",
      "    Image:          hub-mirror.c.163.com/kubernetes/pause:go\n",
      "    Image ID:       docker-pullable://hub-mirror.c.163.com/kubernetes/pause@sha256:b31bfb4d0213f254d361e0079deaaebefa4f82ba7aa76ef82e90b4935ad5b105\n",
      "    Port:           <none>\n",
      "    Host Port:      <none>\n",
      "    State:          Running\n",
      "      Started:      Wed, 24 Jun 2020 17:02:52 +0800\n",
      "    Ready:          True\n",
      "    Restart Count:  0\n",
      "    Environment:    <none>\n",
      "    Mounts:         <none>\n",
      "  istio-proxy:\n",
      "    Container ID:  docker://f1963ed8ca10eaabbbc1deb3e240288d6eb1681891812de89a26387b7ef2c7e8\n",
      "    Image:         docker.io/istio/proxyv2:1.6.3\n",
      "    Image ID:      docker-pullable://istio/proxyv2@sha256:d082c3eea9c12e2f1bf6e4361509453a87e495d12146a1702d79e549098b8951\n",
      "    Port:          15090/TCP\n",
      "    Host Port:     0/TCP\n",
      "    Args:\n",
      "      proxy\n",
      "      sidecar\n",
      "      --domain\n",
      "      $(POD_NAMESPACE).svc.cluster.local\n",
      "      --serviceCluster\n",
      "      iserver-datascience.$(POD_NAMESPACE)\n",
      "      --proxyLogLevel=warning\n",
      "      --proxyComponentLogLevel=misc:error\n",
      "      --trust-domain=cluster.local\n",
      "      --concurrency\n",
      "      2\n",
      "    State:          Waiting\n",
      "      Reason:       CrashLoopBackOff\n",
      "    Last State:     Terminated\n",
      "      Reason:       Error\n",
      "      Exit Code:    1\n",
      "      Started:      Wed, 24 Jun 2020 17:44:33 +0800\n",
      "      Finished:     Wed, 24 Jun 2020 17:44:33 +0800\n",
      "    Ready:          False\n",
      "    Restart Count:  21\n",
      "    Limits:\n",
      "      cpu:     2\n",
      "      memory:  1Gi\n",
      "    Requests:\n",
      "      cpu:      10m\n",
      "      memory:   40Mi\n",
      "    Readiness:  http-get http://:15021/healthz/ready delay=1s timeout=1s period=2s #success=1 #failure=30\n",
      "    Environment:\n",
      "      JWT_POLICY:                    first-party-jwt\n",
      "      PILOT_CERT_PROVIDER:           istiod\n",
      "      CA_ADDR:                       istiod.istio-system.svc:15012\n",
      "      POD_NAME:                      hook-image-puller-9pg6f (v1:metadata.name)\n",
      "      POD_NAMESPACE:                 default (v1:metadata.namespace)\n",
      "      INSTANCE_IP:                    (v1:status.podIP)\n",
      "      SERVICE_ACCOUNT:                (v1:spec.serviceAccountName)\n",
      "      HOST_IP:                        (v1:status.hostIP)\n",
      "      CANONICAL_SERVICE:              (v1:metadata.labels['service.istio.io/canonical-name'])\n",
      "      CANONICAL_REVISION:             (v1:metadata.labels['service.istio.io/canonical-revision'])\n",
      "      PROXY_CONFIG:                  {\"proxyMetadata\":{\"DNS_AGENT\":\"\"}}\n",
      "                                     \n",
      "      ISTIO_META_POD_PORTS:          [\n",
      "                                     ]\n",
      "      ISTIO_META_APP_CONTAINERS:     [\n",
      "                                         pause\n",
      "                                     ]\n",
      "      ISTIO_META_CLUSTER_ID:         Kubernetes\n",
      "      ISTIO_META_INTERCEPTION_MODE:  REDIRECT\n",
      "      ISTIO_META_WORKLOAD_NAME:      hook-image-puller\n",
      "      ISTIO_META_OWNER:              kubernetes://apis/apps/v1/namespaces/default/daemonsets/hook-image-puller\n",
      "      ISTIO_META_MESH_ID:            cluster.local\n",
      "      DNS_AGENT:                     \n",
      "      ISTIO_KUBE_APP_PROBERS:        {}\n",
      "    Mounts:\n",
      "      /etc/istio/pod from istio-podinfo (rw)\n",
      "      /etc/istio/proxy from istio-envoy (rw)\n",
      "      /var/lib/istio/data from istio-data (rw)\n",
      "      /var/run/secrets/istio from istiod-ca-cert (rw)\n",
      "Conditions:\n",
      "  Type              Status\n",
      "  Initialized       True \n",
      "  Ready             False \n",
      "  ContainersReady   False \n",
      "  PodScheduled      True \n",
      "Volumes:\n",
      "  istio-envoy:\n",
      "    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)\n",
      "    Medium:     Memory\n",
      "    SizeLimit:  <unset>\n",
      "  istio-data:\n",
      "    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)\n",
      "    Medium:     \n",
      "    SizeLimit:  <unset>\n",
      "  istio-podinfo:\n",
      "    Type:  DownwardAPI (a volume populated by information about the pod)\n",
      "    Items:\n",
      "      metadata.labels -> labels\n",
      "      metadata.annotations -> annotations\n",
      "  istiod-ca-cert:\n",
      "    Type:        ConfigMap (a volume populated by a ConfigMap)\n",
      "    Name:        istio-ca-root-cert\n",
      "    Optional:    false\n",
      "QoS Class:       Burstable\n",
      "Node-Selectors:  <none>\n",
      "Tolerations:     hub.jupyter.org/dedicated=user:NoSchedule\n",
      "                 hub.jupyter.org_dedicated=user:NoSchedule\n",
      "                 node.kubernetes.io/disk-pressure:NoSchedule\n",
      "                 node.kubernetes.io/memory-pressure:NoSchedule\n",
      "                 node.kubernetes.io/not-ready:NoExecute\n",
      "                 node.kubernetes.io/pid-pressure:NoSchedule\n",
      "                 node.kubernetes.io/unreachable:NoExecute\n",
      "                 node.kubernetes.io/unschedulable:NoSchedule\n",
      "Events:\n",
      "  Type     Reason       Age                    From                Message\n",
      "  ----     ------       ----                   ----                -------\n",
      "  Normal   BackOff      54m (x41 over 64m)     kubelet, openbox00  Back-off pulling image \"hub-mirror.c.163.com/kubernetes/pause:go\"\n",
      "  Warning  BackOff      9m52s (x247 over 64m)  kubelet, openbox00  Back-off restarting failed container\n",
      "  Warning  FailedMount  7m7s (x2 over 7m8s)    kubelet, openbox00  MountVolume.SetUp failed for volume \"istiod-ca-cert\" : failed to sync configmap cache: timed out waiting for the condition\n",
      "  Normal   Created      6m12s (x3 over 7m2s)   kubelet, openbox00  Created container istio-proxy\n",
      "  Normal   Started      6m12s (x3 over 7m2s)   kubelet, openbox00  Started container istio-proxy\n",
      "  Normal   Pulling      5m24s (x4 over 7m5s)   kubelet, openbox00  Pulling image \"docker.io/istio/proxyv2:1.6.3\"\n",
      "  Normal   Pulled       5m20s (x4 over 7m2s)   kubelet, openbox00  Successfully pulled image \"docker.io/istio/proxyv2:1.6.3\"\n",
      "  Warning  BackOff      2m8s (x24 over 7m1s)   kubelet, openbox00  Back-off restarting failed container\n"
     ]
    }
   ],
   "source": [
    "!kubectl describe pod/hook-image-puller-9pg6f"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "NAME           TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE\n",
      "proxy-public   LoadBalancer   10.100.133.24   <pending>     80:31000/TCP,443:31015/TCP   36s\n"
     ]
    }
   ],
   "source": [
    "!kubectl --namespace=gisbook get svc proxy-public"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
